sudo: required

language: C

compiler:
  - clang
  - gcc

git:
  depth: 3

branches:
  only:
    - master

before_install:
  - sudo apt-get install pkg-config
  - sudo apt-get install liblbfgs-dev
  - autoreconf
  - ./configure

install:
  - make
  - sudo make install

script: make check
