sudo: required

language: C

compiler:
  - clang
  - gcc

git:
  depth: 3

branches:
  only:
    - master

install: sudo apt-get install pkg-config && autoconf && ./configure && make all install

script: make check

