sudo: required

dist: bionic

language: C

compiler:
  - gcc

git:
  depth: 3

branches:
  only:
    - master

before_install:
  - sudo apt-get install pkg-config liblbfgs-dev
  - sudo apt-get update -q
  - sudo apt-get install --only-upgrade autoconf
  - autoreconf --force --install
  - ./configure

install:
  - make
  - sudo make install

script: make check
