sudo: required

language: C

compiler:
  - clang
  - gcc

git:
  depth: 3

branches:
  only:
    - master

before_install:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository 'http://hu.archive.ubuntu.com/ubuntu'
  - sudo apt-get update
  - sudo apt-cache policy
  - sudo apt-get install pkg-config liblbfgs-dev
  - autoreconf
  - ./configure

install:
  - make
  - sudo make install

script: make check
apt-cache policy
