sudo: required

language: C

compiler:
  - clang
  - gcc

git:
  depth: 3

branches:
  only:
    - master

before_install:
  - sudo apt-get install pkg-config
  - aclocal
  - autoconf
  - ./configure

install: make all install

script: make check
